# Generated by Django 4.2.5 on 2023-09-17 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(choices=[("BR", "Brazil")], max_length=2)),
                ("state", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                ("street", models.CharField(max_length=256)),
                ("postal_code", models.CharField(max_length=32)),
                ("additional_info", models.CharField(blank=True, max_length=256)),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
