# Generated by Django 4.2.5 on 2023-09-17 17:39

from django.db import migrations, models
import utils.fields
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', utils.fields.ApiCharField(choices=[('BR', 'Brazil')], max_length=2, validators=[utils.validators.validate_safe_characters])),
                ('state', utils.fields.ApiCharField(max_length=64, validators=[utils.validators.validate_safe_characters])),
                ('city', utils.fields.ApiCharField(max_length=64, validators=[utils.validators.validate_safe_characters])),
                ('street', utils.fields.ApiCharField(max_length=256, validators=[utils.validators.validate_safe_characters])),
                ('postal_code', utils.fields.ApiCharField(max_length=32, validators=[utils.validators.validate_safe_characters])),
                ('additional_info', utils.fields.ApiCharField(blank=True, max_length=256, validators=[utils.validators.validate_safe_characters])),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
