# Generated by Django 4.2.5 on 2023-09-17 23:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("identifier", models.CharField(db_index=True, max_length=32)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[("CPF", "Cpf"), ("CNPJ", "Cnpj")], max_length=4
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="address.address",
                        verbose_name="Addresses",
                    ),
                ),
            ],
        ),
    ]
