# Generated by Django 4.2.5 on 2023-09-17 17:39

from django.db import migrations, models
import django.db.models.deletion
import utils.fields
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', utils.fields.ApiCharField(max_length=128, validators=[utils.validators.validate_safe_characters])),
                ('identifier', utils.fields.ApiCharField(db_index=True, max_length=32, validators=[utils.validators.validate_safe_characters])),
                ('identifier_type', utils.fields.ApiCharField(choices=[('CPF', 'Cpf'), ('CNPJ', 'Cnpj')], max_length=4, validators=[utils.validators.validate_safe_characters])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Addresses')),
            ],
        ),
    ]
